config/urls.py
from typing import Any

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.urls import include, path
from django.views import defaults as default_views
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import Sitemap as wagtail_sitemap_view
from wagtail.documents import urls as wagtaildocs_urls

from django_wtf.core.views import sitemaps as core_sitemaps

sitemaps = {**core_sitemaps, "blog": wagtail_sitemap_view}


urlpatterns: list[Any] = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django_wtf.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Health checks
    path("health/", include("health_check.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path(
        "sitemap.xml",
        sitemap_view,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("blog/", include(wagtail_urls)),
    path("", include("django_wtf.core.urls")),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]
        urlpatterns = [
            path("__reload__/", include("django_browser_reload.urls")),
            *urlpatterns,
        ]

django_wtf/core/urls.py
from django.urls import path

from django_wtf.core.search_view import SearchView
from django_wtf.core.views import (
    CategoryView,
    IndexView,
    SocialMediaNewsView,
    TopProfilesView,
    TopRepositoriesView,
    TrendingProfilesView,
    TrendingRepositoriesView,
    create_email_subscriber_view,
    email_subscriber_landing_view,
    repo_detail_view,
)

app_name = "core"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path(
        "trending/",
        view=TrendingRepositoriesView.as_view(),
        name="trending-repositories",
    ),
    path(
        "top/",
        view=TopRepositoriesView.as_view(),
        name="top-repositories",
    ),
    path("repo/<path:full_name>", view=repo_detail_view, name="repo-detail"),
    path(
        "social-media-news/",
        view=SocialMediaNewsView.as_view(),
        name="social-media-news",
    ),
    path("profiles/top/", view=TopProfilesView.as_view(), name="top-profiles"),
    path(
        "profiles/trending/",
        view=TrendingProfilesView.as_view(),
        name="trending-profiles",
    ),
    path("category/<slug:name>/", view=CategoryView.as_view(), name="category-detail"),
    path("search/", view=SearchView.as_view(), name="search"),
    path(
        "newsletter/",
        view=email_subscriber_landing_view,
        name="subscriber-landing",
    ),
    path(
        "subscriber-create/",
        view=create_email_subscriber_view,
        name="subscriber-create",
    ),
]

django_wtf/users/urls.py
from django.urls import path

from django_wtf.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

django_wtf/core/models/category_model.py
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


class Category(TimeStampedModel):
    name = models.CharField(max_length=50, unique=True)
    emoji = models.CharField(max_length=5)

    def __str__(self):
        return f"<Category: {self.name}>"

    def get_absolute_url(self):
        return reverse("core:category-detail", args=[self.name])

django_wtf/core/models/contributor_model.py
from django.db import models
from model_utils.models import TimeStampedModel


class Contributor(TimeStampedModel):
    profile = models.ForeignKey(
        "core.Profile",
        on_delete=models.CASCADE,
    )
    repository = models.ForeignKey(
        "core.Repository",
        on_delete=models.CASCADE,
        related_name="contributors",
        related_query_name="contributor",
    )
    contributions = models.PositiveIntegerField()

    def __str__(self):
        return f"<Contributor {self.profile.login} to {self.repository.full_name}>"

django_wtf/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

django_wtf/core/views/category_view.py
from django.core.paginator import Paginator
from django.views.generic import DetailView
from meta.views import MetadataMixin

from django_wtf.core.models import Category, Repository


class CategoryView(MetadataMixin, DetailView):
    model = Category

    def get_object(self, *args, **kwargs):
        return Category.objects.get(name=self.kwargs.get("name"))

    def get_context_data(self, *, _=None, **kwargs):  # pylint: disable=arguments-differ
        context = super().get_context_data()
        repos = self.matching_repositories()
        paginator = Paginator(repos, 25)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["paginator"] = paginator
        context["page_obj"] = page_obj
        context["category"] = self.get_object()
        return context

    def get_meta_title(self, context=None):
        return f"Django.WTF | {self.category_name}"

    def get_meta_description(self, context=None):
        repos = self.matching_repositories()
        repo_names = ", ".join([r.full_name for r in repos[0:10]])
        return f"Common apps used for {self.category_name} are: {repo_names}"

    def matching_repositories(self):
        repos = Repository.valid.filter(categories__name=self.category_name).distinct()
        repos = repos.order_by("-stars")
        return repos

    @property
    def category_name(self):
        return self.kwargs.get("name")

django_wtf/core/views/detail_view.py
from datetime import timedelta

from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView

from django_wtf.core.models import Repository


class RepoDetailView(DetailView):
    def get_object(self, queryset=None):
        return get_object_or_404(Repository, full_name=self.kwargs.get("full_name"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        stars_since_1m = obj.stars_since(since=timedelta(days=30))
        context["stars_increase_monthly_percent"] = stars_since_1m / obj.stars * 100.0
        return context


repo_detail_view = RepoDetailView.as_view()

django_wtf/core/views/email_subscribe_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from django_wtf.core.models import EmailSubscriber


class EmailSubscriberLandingView(TemplateView):
    template_name = "core/email_subscriber_landing.html"


email_subscriber_landing_view = EmailSubscriberLandingView.as_view()


class CreateEmailSubscriberView(LoginRequiredMixin, RedirectView):
    permanent = False
    url = reverse_lazy("core:index")
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        _, _ = EmailSubscriber.objects.get_or_create(user=self.request.user)
        emailaddress = user.emailaddress_set.get(primary=True)  # type: ignore
        email = EmailMessage(
            subject="Subscription confirmed to Django.WTF",
            body="""Woohoo!

I'll update you with trending projects and news from the Django world every two weeks.

Thanks,
The people behind Django.WTF
""",
            from_email="noreply@django.wtf",
            to=[emailaddress.email],
            reply_to=["noreply@django.wtf"],
        )
        email.send()
        messages.success(
            self.request,
            "We will send you email updates every other week on trending repositories.",
        )

        return super().get_redirect_url(*args, **kwargs)


create_email_subscriber_view = CreateEmailSubscriberView.as_view()

django_wtf/core/views/index_view.py
from django.templatetags.static import static
from django.views.generic.base import TemplateView
from meta.views import MetadataMixin

from django_wtf.core.models import Category, Repository, SocialNews
from django_wtf.core.queries import (
    one_week_ago,
    trending_profiles,
    trending_repositories,
)


def categories_ordered_by_total_repositories():
    categories = []
    for c in Category.objects.all():
        count_matching_repositories = Repository.objects.filter(
            categories__in=[c]
        ).count()
        if count_matching_repositories:
            setattr(c, "total_repositories", count_matching_repositories)
            categories.append(c)
    return sorted(categories, key=lambda c: c.total_repositories, reverse=True)


class IndexView(MetadataMixin, TemplateView):
    template_name = "core/index.html"
    title = "Django.WTF: The Django package index"
    description = (
        "Django.WTF lists popular Django projects, apps and tools. "
        "The latest and greatest news in the Django community."
    )
    keywords = [
        "django",
        "apps",
        "packages",
        "repositories",
        "python",
        "web",
        "framework",
        "apps",
        "tools",
        "news",
    ]
    use_schemaorg = True
    use_og = True
    use_twitter = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = categories_ordered_by_total_repositories()
        context["trending_apps"] = trending_repositories(days_since=14)[0:5]
        context["trending_developers"] = trending_profiles()[0:5]
        context["social_news"] = SocialNews.objects.filter(
            created_at__gt=one_week_ago
        ).order_by("-upvotes")[0:5]
        context["top_apps"] = Repository.valid.order_by("-stars")[0:5]
        return context

    def get_meta_image(self, context=None):
        return static("images/logo.png")

django_wtf/core/views/sitemap_views.py
from django.contrib.sitemaps import GenericSitemap, Sitemap
from django.urls import reverse

from django_wtf.core.models import Category, Repository


class StaticSitemap(Sitemap):
    priority = 0.5
    changefreq = "daily"

    def items(self):
        return [
            "core:index",
            "core:top-profiles",
            "core:trending-profiles",
            "core:top-repositories",
            "core:trending-repositories",
            "core:social-media-news",
        ]

    def location(self, item):
        return reverse(item)


category_sitemap = GenericSitemap(  # type: ignore
    {"queryset": Category.objects.all(), "changefreq": "daily"}  # type: ignore
)

detail_sitemap = GenericSitemap(  # type: ignore
    {"queryset": Repository.valid.all(), "changefreq": "daily"}  # type: ignore
)


sitemaps = {
    "static": StaticSitemap,
    "categories": category_sitemap,
    "repos": detail_sitemap,
}

django_wtf/core/views/social_media_news_view.py
from django.views.generic import ListView
from meta.views import MetadataMixin

from django_wtf.core.models import SocialNews
from django_wtf.core.queries import one_week_ago


class SocialMediaNewsView(MetadataMixin, ListView):
    paginate_by = 25
    title = "Django News"
    description = "Django social media news"
    template_name = "core/social_media_news.html"

    def get_queryset(self):
        return SocialNews.objects.filter(created_at__gt=one_week_ago).order_by(
            "-upvotes"
        )

django_wtf/core/views/test_email_subscribe_views.py
import pytest
from allauth.account.models import EmailAddress
from django.contrib.messages import get_messages
from django.urls.base import reverse
from pytest_django.asserts import assertRedirects

from django_wtf.core.models import EmailSubscriber

url = reverse("core:subscriber-create")

pytestmark = pytest.mark.django_db


def test_create_email_subscriberview(user_client, mailoutbox):
    EmailAddress.objects.create(
        user=user_client.user, verified=True, primary=True, email="bob@gmail.com"
    )
    res = user_client.post(url, follow=True)

    assertRedirects(
        res,
        reverse("core:index"),
        status_code=302,
        target_status_code=200,
        fetch_redirect_response=True,
    )

    assert EmailSubscriber.objects.filter(user=user_client.user).count() == 1
    assert len(mailoutbox) == 1
    mail = mailoutbox[0]
    assert mail.subject == "Subscription confirmed to Django.WTF"
    assert mail.to == ["bob@gmail.com"]
    assert (
        mail.body
        == """Woohoo!

I'll update you with trending projects and news from the Django world every two weeks.

Thanks,
The people behind Django.WTF
"""
    )

    messages = list(get_messages(res.wsgi_request))
    assert (
        messages[0].message
        == "We will send you email updates every other week on trending repositories."
    )


def test_only_creates_one_subscriber(user_client):
    EmailAddress.objects.create(
        user=user_client.user, verified=True, primary=True, email="bob@gmail.com"
    )
    res = user_client.post(url, follow=True)
    assertRedirects(
        res,
        reverse("core:index"),
    )
    res = user_client.post(url, follow=True)
    assertRedirects(
        res,
        reverse("core:index"),
    )
    assert EmailSubscriber.objects.filter(user=user_client.user).count() == 1

django_wtf/core/views/test_index_view.py
import pytest
from django.urls import reverse_lazy

from django_wtf.core.factories import RepositoryFactory
from django_wtf.core.models import Category, RepositoryType

pytestmark = pytest.mark.django_db
url = reverse_lazy("core:index")


def test_index_lists_top_apps(client):
    RepositoryFactory(
        full_name="danihodovic/celery-exporter",
        stars=1,
        categories=[],
        type=RepositoryType.APP,
    )
    RepositoryFactory(
        full_name="getsentry/sentry",
        stars=100,
        categories=(
            Category(name="projects", emoji="p"),
            Category(name="monitoring", emoji="m"),
        ),
        type=RepositoryType.PROJECT,
    )
    res = client.get(url)
    assert res.status_code == 200
    top_apps = res.context["top_apps"]
    assert len(top_apps) == 2
    assert top_apps[0].full_name == "getsentry/sentry"
    assert top_apps[1].full_name == "danihodovic/celery-exporter"

django_wtf/core/views/test_trending_repositories_view.py
from datetime import datetime, timedelta

import pytest
from django.urls import reverse

pytestmark = pytest.mark.django_db


def test_trending_by_week(
    valid_repository_factory, repository_stars_factory, user_client
):
    now = datetime.now()
    seven_days_ago = now - timedelta(days=7)
    url = reverse("core:trending-repositories")
    more_popular = valid_repository_factory(stars=32)
    less_popular = valid_repository_factory(stars=40)
    repository_stars_factory(
        repository=more_popular, created_at=seven_days_ago, stars=2
    )
    repository_stars_factory(
        repository=less_popular, created_at=seven_days_ago, stars=10
    )

    res = user_client.get(url + "?trending=7")
    assert res.context["object_list"][0] == more_popular
    assert res.context["object_list"][1] == less_popular
    assert res.context["object_list"][0].stars_gained == 30
    assert res.context["object_list"][0].percentage_increase == 1500.0
    assert res.context["object_list"][1].stars_gained == 30
    assert res.context["object_list"][1].percentage_increase == 300

django_wtf/core/views/top_profiles_view.py
from django.views.generic import ListView
from meta.views import MetadataMixin

from django_wtf.core.queries import most_followed_profiles


class TopProfilesView(MetadataMixin, ListView):
    template_name = "core/top_profiles.html"
    paginate_by = 25
    title = "Top contributors to Django projects"
    description = "Listing the top contributors to Django projects"

    def get_queryset(self):
        return most_followed_profiles()

django_wtf/templates/core/base.html
{% load tailwind_tags django_htmx %}
<!DOCTYPE html>
<html lang="en-US">
    <head>
        {% block head %}
            {% include "meta/meta.html" %}
            {% tailwind_css %}
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
                  rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Akshar:wght@300;400&display=swap"
                  rel="stylesheet">
        {% endblock head %}
    </head>
    <body class="font-roboto flex min-h-screen w-screen flex-col content-center justify-start lg:w-full">
        {% include "core/components/_navbar.html" %}
        {% if messages %}
            <div class="mx-auto mt-3">
                {% for message in messages %}
                    <div role="alert" class="alert alert-{{ message.tags }}">
                        <span>{{ message }}</span>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="flex w-full flex-col content-center self-center">
            {% block content %}
            {% endblock content %}
        </div>
        {% include "core/components/_footer.html" %}
        {% if not debug %}
            <noscript>
                <img alt="django-wtf logo"
                     src="https://s.depode.com/ingress/7ca0f5ff-8ef2-45fb-9718-37d34cddfe79/pixel.gif">
            </noscript>
            <script defer
                    src="https://s.depode.com/ingress/7ca0f5ff-8ef2-45fb-9718-37d34cddfe79/script.js"></script>
            <script defer
                    src="https://analytics-umami.honeylogic.io/script.js"
                    data-website-id="4156089c-d947-4313-9d54-4d8f8f99d237"></script>
        {% endif %}
        <script src="https://unpkg.com/htmx.org@1.9.11"></script>
        {% django_htmx_script %}
    </body>
    {% block js %}
    {% endblock js %}
</html>

django_wtf/templates/core/category_detail.html
{% extends "core/base.html" %}
{% load user_agents %}
{% block content %}
    <div class="flex flex-col self-center items-center p-4 lg:p-6 w-full lg:w-11/12">
        <div class="flex flex-wrap flex-row self-start mt-3 mb-10 text-sm lg:text-lg gap-2">
            <a href="{% url 'core:category-detail' name=category.name %}"
               class="flex flex-wrap gap-2 hover:brightness-125">
                <div class="badge badge-lg badge-primary">{{ category.emoji }} {{ category.name }}</div>
                <div class="badge badge-lg badge-primary">
                    {{ page_obj.paginator.count }} matching repositor{{ page_obj.paginator.count | pluralize:"ies" }}
                </div>
            </a>
        </div>
        <table class="table table-compact lg:table-normal w-full mb-5">
            <thead>
                <tr>
                    <th class="hidden xl:block">Rank</th>
                    <th>Name</th>
                    <th class="hidden xl:block">Description</th>
                    <th>Stars</th>
                </tr>
            </thead>
            <tbody>
                {% for repo in page_obj %}
                    <tr class="hover">
                        {% url 'core:repo-detail' full_name=repo.full_name as url %}
                        <td class="hidden xl:table-cell">
                            <a class="font-bold" href="{{ url }}" target="_blank">{{ page_obj.start_index|add:forloop.counter0 }}</a>
                        </td>
                        <td>
                            <a href="{{ url }}" target="_blank">
                                {% if request|is_mobile or request|is_tablet %}
                                    {{ repo.full_name|truncatechars:30 }}
                                {% else %}
                                    {{ repo.full_name }}
                                {% endif %}
                            </a>
                        </td>
                        <td class="hidden xl:table-cell">
                            <div class="tooltip tooltip-primary before:content-[attr(data-tip)] before:max-w-[50rem]"
                                 data-tip="{{ repo.truncated_description }}">
                                <a href="{{ url }}" target="_blank">{{ repo.truncated_description|truncatechars:60 }}</a>
                            </div>
                        </td>
                        <td>
                            <a href="{{ url }}" target="_blank">{{ repo.stars }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "core/components/pagination.html" %}
    </div>
{% endblock content %}

django_wtf/templates/core/search.html
{% extends "core/base.html" %}
{% block content %}
    <div class="mb-5 flex-col self-center w-11/12 lg:mt-5 lg:flex lg:w-7/12">
        <form class="form lg:flex lg:justify-between">
            <label class="form-control">
                <div class="label">
                    <span class="label-text">Search</span>
                </div>
                <input type="text"
                       name="q"
                       value="{{ request.GET.q }}"
                       hx-include="[name='category']"
                       hx-get="{% url 'core:search' %}"
                       hx-push-url="true"
                       hx-target="#search_table"
                       hx-trigger="keyup changed delay:0.5s"
                       class="input input-bordered min-w-64" />
            </label>
            <div class="flex gap-4">
                <label class="form-control">
                    <div class="label">
                        <span class="label-text">Category</span>
                    </div>
                    <select name="category"
                            class="select select-bordered"
                            hx-trigger="change"
                            hx-include="[name='q']"
                            hx-get="{% url 'core:search' %}"
                            hx-push-url="true"
                            hx-target="#search_table">
                        <option>All</option>
                        {% for category in categories %}
                            <option value="{{ category.name }}"
                                    {% if category.name == request.GET.category %}selected{% endif %}>
                                {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </label>
            </div>
        </form>
        <div id="search_table" class="mt-7">{% include "core/search_table.html" %}</div>
    </div>
{% endblock content %}

django_wtf/templates/core/search_table.html
{% load admin_urls static %}

{% if object_list %}
    {% for object in page_obj %}
        <div class="my-4 rounded">
            <div class="shadow-xl card bg-base-200">
                <div class="pb-2 card-body">
                    <a target="_blank"
                       href="{% url 'core:repo-detail' full_name=object.full_name %}">
                        <h2 class="flex justify-between card-title">
                            <span>{{ object.full_name }}</span>
                            <span class="text-sm">⭐ {{ object.stars }}</span>
                        </h2>
                    </a>
                    <div class="flex flex-wrap gap-2">
                        {% for topic in object.topics|slice:"0:5" %}
                            <a class="text-xs badge badge-outline hover:brightness-125"
                               href="{% url 'core:search' %}?q={{ topic }}">{{ topic|truncatechars:30 }}</a>
                        {% endfor %}
                    </div>
                    <p class="mt-2">{{ object.description }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if paginator.num_pages > 1 %}
        <div class="flex w-100 justify-center mt-10 mb-5">
            <div class="join">
                {% if page_obj.has_previous %}
                    <button class="join-item btn btn-neutral"
                            hx-trigger="click"
                            hx-include="[name='q'],[name='category']"
                            hx-get="{% url 'core:search' %}?page={{ page_obj.previous_page_number }}"
                            hx-push-url="true"
                            hx-target="#search_table">
                        <<
                    </button>
                    {% if page_obj.number > 2 %}
                        <button class="join-item btn btn-neutral mr-3"
                                hx-trigger="click"
                                hx-include="[name='q'],[name='category']"
                                hx-get="{% url 'core:search' %}?page=1"
                                hx-push-url="true"
                                hx-target="#search_table">1</button>
                    {% endif %}
                    <button class="join-item btn btn-neutral"
                            hx-trigger="click"
                            hx-include="[name='q'],[name='category']"
                            hx-get="{% url 'core:search' %}?page={{ page_obj.previous_page_number }}"
                            hx-push-url="true"
                            hx-target="#search_table">{{ page_obj.previous_page_number }}</button>
                {% endif %}
                <button class="join-item btn btn-neutral btn-active">{{ page_obj.number }}</button>
                {% if page_obj.has_next %}
                    <button class="join-item btn btn-neutral"
                            hx-trigger="click"
                            hx-include="[name='q'],[name='category']"
                            hx-get="{% url 'core:search' %}?page={{ page_obj.next_page_number }}"
                            hx-push-url="true"
                            hx-target="#search_table">{{ page_obj.next_page_number }}</button>
                    <button class="join-item btn btn-neutral"
                            hx-trigger="click"
                            hx-include="[name='q'],[name='category']"
                            hx-get="{% url 'core:search' %}?page={{ page_obj.next_page_number }}"
                            hx-push-url="true"
                            hx-target="#search_table">>></button>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endif %}

django_wtf/templates/core/top_repositories.html
{% extends "core/base.html" %}
{% load user_agents %}
{% block content %}
    <div class="flex w-full flex-col items-center self-center p-4 lg:w-7/12 lg:p-6">
        <div class="mb-10 mt-3 flex flex-wrap gap-2 self-start text-sm lg:text-lg">
            <div class="badge badge-lg badge-primary">Top repositories</div>
            <div class="badge badge-lg badge-primary">Repositories with the most stars</div>
        </div>
        <table class="mb-5 table w-full leading-6">
            <thead>
                <tr>
                    <th class="hidden xl:block">Rank</th>
                    <th>Name</th>
                    <th class="hidden xl:block">Description</th>
                    <th>Stars</th>
                </tr>
            </thead>
            <tbody>
                {% for repo in page_obj %}
                    <tr class="hover">
                        {% url 'core:repo-detail' full_name=repo.full_name as url %}
                        <td class="hidden xl:table-cell">
                            <a class="font-bold" href="{{ url }}" target="_blank">{{ page_obj.start_index|add:forloop.counter0 }}</a>
                        </td>
                        <td>
                            <a href="{{ url }}" target="_blank">
                                {% if request|is_mobile or request|is_tablet %}
                                    {{ repo.full_name|truncatechars:25 }}
                                {% else %}
                                    {{ repo.full_name }}
                                {% endif %}
                            </a>
                        </td>
                        <td class="hidden xl:table-cell">
                            <a href="{{ url }}" target="_blank">{{ repo.truncated_description|truncatechars:50 }}</a>
                        </td>
                        <td>
                            <a href="{{ url }}" target="_blank">{{ repo.stars }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "core/components/pagination.html" %}
    </div>
{% endblock content %}
{% block stars_column_header %}
{% endblock stars_column_header %}